services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: electricidad_backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@192.168.1.130:1521/ORCLPDB1
      - SPRING_DATASOURCE_USERNAME=APP_ELECTRICIDAD
      - SPRING_DATASOURCE_PASSWORD=Oracle123
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.OracleDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
    ports:
      - "8090:8080"
    networks:
      - app-net

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: electricidad_frontend
    ports:
      - "8181:80"
    depends_on:
      - backend
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
